site_name: Open-SmartWatch
theme: readthedocs
site_url: http://open-smartwatch.github.io/

markdown_extensions:
  - admonition

nav:
  - "Home": "index.md"
  - "Firmware": [] # This section was moved into the OSW-OS repository

extra_css:
  - stylesheets/tags.css
  - stylesheets/max-width.css
